### PR TITLE
Handle NodeJS stacktraces

### PR DESCRIPTION
**Pull request by MrMineO5**

### CODE REVIEW

**Comment by MrMineO5** [comment]
Your test has the : in c:/, which causes an exception when resolving the line number from the source string. I remove that : in the nodejs probe so it ends up as /c/path instead of file:///c:/path

**Comment by BFergerson** [comment]
I took that stack trace off StackOverflow to use a real example. I looked around for other examples but they all looked the same. If you have a legit stack trace that this won't work for we can expand the logic. I don't think you should manipulate the stack trace to make it easier to parse. I'd like this logic to work on the original data so it can be used elsewhere.

Please give provide example stack traces that don't work and I'll add tests.

**Comment by MrMineO5** [comment]
I think calling LiveStackTraceElement#sourceAsLineNumber on that stack trace should throw an exception, since it takes everything after the first :

**Comment by BFergerson** [comment]
Ah, I see what you mean. I'll expand the tests, thanks.

**Pull request merged**
